"""Added created_at column

Revision ID: 83a7966cb79b
Revises: 
Create Date: 2024-12-02 03:38:30.726871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83a7966cb79b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_data', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
